{
 "title": "Cilium / Cilium Metrics",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "tags": [ "cilium" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_created{pod=~\"^cilium-[a-z|A-Z|0-9]+$\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Errors & Warnings",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_errors_warnings_total{k8s_app=\"cilium\"}[1m])) by (pod, level) * 60",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "CPU Usage per node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\"}[1m])) by (pod) * 100",
     "legendFormat": "min"
    },
    {
     "expr": "avg(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\"}[1m])) by (pod) * 100",
     "legendFormat": "avg"
    },
    {
     "expr": "max(irate(cilium_process_cpu_seconds_total{k8s_app=\"cilium\"}[1m])) by (pod) * 100",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Generic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Virtual Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "Min Virtual Memory"
    },
    {
     "expr": "avg(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "Average Virtual Memory"
    },
    {
     "expr": "max(cilium_process_virtual_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "Max Virtual Memory"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_process_resident_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "AVG_resident_memory_bytes"
    },
    {
     "expr": "max(cilium_process_resident_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "MAX_resident_memory_bytes_max"
    },
    {
     "expr": "min(cilium_process_resident_memory_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "MIN_resident_memory_bytes_min"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_process_open_fds{k8s_app=\"cilium\"})",
     "legendFormat": "all nodes"
    },
    {
     "expr": "min(cilium_process_open_fds{k8s_app=\"cilium\"})",
     "legendFormat": "min/node"
    },
    {
     "expr": "avg(cilium_process_open_fds{k8s_app=\"cilium\"})",
     "legendFormat": "avg/node"
    },
    {
     "expr": "max(cilium_process_open_fds{k8s_app=\"cilium\"})",
     "legendFormat": "max/node"
    }
   ]
  },
  {
   "title": "System-wide BPF memory usage",
   "type": "graph",
   "description": "BPF memory usage in the entire system including components not managed by Cilium.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "AVG_bpf_memory_bytes_avg"
    },
    {
     "expr": "max(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "MAX_bpf_memory_bytes_max"
    },
    {
     "expr": "min(cilium_bpf_maps_virtual_memory_max_bytes{k8s_app=\"cilium\"} + cilium_bpf_progs_virtual_memory_max_bytes{k8s_app=\"cilium\"})",
     "legendFormat": "MIN_bpf_memory_bytes_min"
    }
   ]
  },
  {
   "title": "BPF map pressure",
   "type": "graph",
   "description": "Fill percentage of BPF maps, tagged by map name",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "cilium_bpf_map_pressure" }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "API call latency (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "API call latency (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "# API calls (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "# API calls (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "API return codes (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}} )"
    }
   ]
  },
  {
   "title": "API return codes (sum all nodes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}} )"
    }
   ]
  },
  { "title": "Cilium", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  { "title": "BPF", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "# system calls (average node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "# system calls (max node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "system call latency (avg node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_bpf_syscall_duration_seconds_sum{k8s_app=\"cilium\"}[1m])/ rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "system call latency (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_bpf_syscall_duration_seconds_sum{k8s_app=\"cilium\"}[1m])/ rate(cilium_bpf_syscall_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "map ops (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\"}[5m])) by (pod, map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "map ops (max node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\"}[5m])) by (pod, map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "map ops (sum failures)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_bpf_map_ops_total{k8s_app=\"cilium\",outcome=\"fail\"}[5m])) by (pod, map_name, operation)",
     "legendFormat": "{{map_name}} {{operation}}"
    }
   ]
  },
  { "title": "kvstore", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "# operations (sum all nodes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kvstore_operations_total{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, scope, action)",
     "legendFormat": "{{scope}} {{action}}"
    }
   ]
  },
  {
   "title": "# operations (max node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(kvstore_operations_total{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, scope, action)",
     "legendFormat": "{{scope}} {{action}}"
    }
   ]
  },
  {
   "title": "latency (average node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_kvstore_operations_duration_seconds_sum{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, action, scope))",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "latency (max node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_kvstore_operations_duration_seconds_sum{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, action, scope))",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Events received (average node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kvstore_events_queue_seconds_count{kubernetes_pod_name=~\"$pod\"}[1m])) by (pod, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  { "title": "Cilium network information", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Forwarded Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_count_total{k8s_app=\"cilium\"}[1m])) by (pod, direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Forwarded Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_bytes_total{k8s_app=\"cilium\"}[1m])) by (pod, direction) * 8",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack TCP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack TCP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack Non-TCP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack Non-TCP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{k8s_app=\"cilium\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\"}) by (family,status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "Allocated Addresses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_ip_addresses{k8s_app=\"cilium\"}) by (pod, family)\n",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Datapath Conntrack Dump Resets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_datapath_conntrack_dump_resets_total{k8s_app=\"cilium\"}) by (pod, area, family, name)",
     "legendFormat": "{{name}} {{area}} {{family}}"
    }
   ]
  },
  {
   "title": "Service Updates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_services_events_total{k8s_app=\"cilium\"}[1m])) by (pod, action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Connectivity Health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_unreachable_nodes{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "unreachable nodes"
    },
    {
     "expr": "sum(cilium_unreachable_health_endpoints{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "unreachable health endpoints"
    }
   ]
  },
  {
   "title": "Dropped Egress Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"EGRESS\", k8s_app=\"cilium\"}[1m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_nodes_all_events_received_total{k8s_app=\"cilium\"}[1m])) by (pod, event_type, source) * 60",
     "legendFormat": "{{eventType}} {{source}}"
    }
   ]
  },
  {
   "title": "Dropped Egress Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"EGRESS\", k8s_app=\"cilium\"}[1m])) by (reason) * 8",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_nodes_all_num{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "Average Nodes"
    },
    {
     "expr": "min(cilium_nodes_all_num{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "Min Nodes"
    },
    {
     "expr": "max(cilium_nodes_all_num{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "Max Nodes"
    }
   ]
  },
  { "title": "Policy", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "L7 forwarded request",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_denied_total{k8s_app=\"cilium\"}[1m]))",
     "legendFormat": "denied"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_forwarded_total{k8s_app=\"cilium\"}[1m]))",
     "legendFormat": "forwarded"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_received_total{k8s_app=\"cilium\"}[1m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Cilium drops Ingress",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"INGRESS\", k8s_app=\"cilium\"}[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Proxy response time (Avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_sum{k8s_app=\"cilium\"}[1m])) by (pod, scope) / sum(rate(cilium_proxy_upstream_reply_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, scope)",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg(cilium_policy_l7_parse_errors_total{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "parse errors"
    }
   ]
  },
  {
   "title": "Dropped Ingress Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"INGRESS\", k8s_app=\"cilium\"}[1m])) by (reason) * 8",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Policy Trigger Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "min(rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\"}[1m])) by (pod, scope) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, scope)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\"}[1m])) by (pod, scope) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, scope)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\"}[1m])) by (pod, scope) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, scope)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Proxy response time (Max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_proxy_upstream_reply_seconds_sum{k8s_app=\"cilium\"}[1m])) by (pod, scope) / sum(rate(cilium_proxy_upstream_reply_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, scope)",
     "legendFormat": "Max {{scope}}"
    },
    {
     "expr": "max(rate(cilium_policy_l7_parse_errors_total{k8s_app=\"cilium\"}[1m])) by (pod)",
     "legendFormat": "parse errors"
    }
   ]
  },
  {
   "title": "Endpoints policy enforcement status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_policy_endpoint_enforcement_status{k8s_app=\"cilium\"}) by (enforcement)",
     "legendFormat": "{{enforcement}}"
    }
   ]
  },
  {
   "title": "Proxy Redirects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_proxy_redirects{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_proxy_redirects{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_proxy_redirects{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Policy Trigger Runs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "min(rate(cilium_triggers_policy_update_total{k8s_app=\"cilium\"}[1m])) by (pod) * 60",
     "legendFormat": "min trigger"
    },
    {
     "expr": "avg(rate(cilium_triggers_policy_update_total{k8s_app=\"cilium\"}[1m])) by (pod) * 60",
     "legendFormat": "average trigger"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_total{k8s_app=\"cilium\"}[1m])) by (pod) * 60",
     "legendFormat": "max trigger"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_folds{k8s_app=\"cilium\"}[1m])) by (pod) * 60",
     "legendFormat": "folds"
    }
   ]
  },
  {
   "title": "Policies Per Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_policy{k8s_app=\"cilium\"}) by(pod)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_policy{k8s_app=\"cilium\"}) by(pod)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_policy{k8s_app=\"cilium\"}) by(pod)",
     "legendFormat": "max"
    },
    {
     "expr": "sum(cilium_policy_import_errors_total{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "policy import errors"
    }
   ]
  },
  {
   "title": "DNS proxy requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Policy Revision",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(cilium_policy_max_revision{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_policy_max_revision{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_policy_max_revision{k8s_app=\"cilium\"}) by (pod)",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Endpoints", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Endpoint regeneration time (90th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{k8s_app=\"cilium\", scope!=\"total\"}[5m]))) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regeneration time (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{k8s_app=\"cilium\", scope!=\"total\"}[5m]))) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regenerations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_endpoint_regenerations_total{k8s_app=\"cilium\"}[30s])) by(outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Cilium endpoint state",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{k8s_app=\"cilium\"}) by (endpoint_state)",
     "legendFormat": "{{endpoint_state}}"
    }
   ]
  },
  { "title": "Controllers", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "Controllers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_total{k8s_app=\"cilium\"}[1m])) by (pod)",
     "legendFormat": "Runs"
    },
    {
     "expr": "sum(cilium_controllers_failing{k8s_app=\"cilium\"}) by(pod)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Controller Durations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 161 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_duration_seconds_sum{k8s_app=\"cilium\"}[1m])) by (pod, status) / sum(rate(cilium_controllers_runs_duration_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Kubernetes integration", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "apiserver latency (average node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_k8s_client_api_latency_time_seconds_sum{k8s_app=\"cilium\"}[1m])/rate(cilium_k8s_client_api_latency_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "apiserver latency (max node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(cilium_k8s_client_api_latency_time_seconds_sum{k8s_app=\"cilium\"}[1m])/rate(cilium_k8s_client_api_latency_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "apiserver #calls (sum all nodes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_latency_time_seconds_count{k8s_app=\"cilium\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "apiserver calls (sum all nodes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_calls_total{k8s_app=\"cilium\"}[1m])) by (pod, method, return_code)",
     "legendFormat": "{{method}} {{return_code}}"
    }
   ]
  },
  {
   "title": "Valid, Unnecessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"true\", valid=\"true\"}[5m])) by (pod, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Invalid, Unnecessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"true\", valid=\"false\"}[5m])) by (pod, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Valid, Necessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"false\", valid=\"true\"}[5m])) by (pod, scope, action, valid)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Invalid, Necessary K8s Events Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{k8s_app=\"cilium\", equal=\"false\", valid=\"false\"}[5m])) by (pod, scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "CiliumNetworkPolicy Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 196 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"CiliumNetworkPolicy\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "NetworkPolicy Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 196 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"NetworkPolicy\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Pod Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Pod\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 203 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Node\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Service Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Service\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Endpoints Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 210 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Endpoint\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Namespace Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{k8s_app=\"cilium\", scope=\"Namespace\"}[1m])) by (pod, action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}