bases:
  - environments.yaml
---
repositories:
  - name: "metrics-server"
    url: "https://kubernetes-sigs.github.io/metrics-server/"

releases:
  - name: "metrics-server"
    chart: "metrics-server/metrics-server"
    version: {{ .Values.chart_version | quote }}
    wait: true
    timeout: 180
    atomic: true
    cleanupOnFail: true
    installed: {{ .Values.installed }}
    namespace: {{ .Values.namespace | quote }}
    values:
      - args: {{ .Values.args }}
